### PR TITLE
Add support for SBT 1.x

### PR DESCRIPTION
**Pull request by macalinao**
Fixes https://github.com/ohnosequences/sbt-s3-resolver/issues/50.

### CODE REVIEW

**Comment by laughedelic** [comment]
Thanks @macalinao! I'll check it tonight and publish.

**Comment by laughedelic** [comment]
Cool. Thanks for contributing it @macalinao 👍

**Comment by macalinao** [comment]
Np, wasn't sure if i had to do anything special for cross compiling btw

**Comment by laughedelic** [comment]
I wasn't sure about it either and just decided to drop sbt-0.13. There was a point to cross-compile/publish when sbt-1.0 wasn't ready, so people could prepare for the migration. Now that sbt-1.0 is official, we should be all switching to it (and those stuck at 0.13 for some reason can always use an old version).

**Pull request merged**
